# Generated by Django 4.1.3 on 2022-12-17 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_newsstory_favourited_by_alter_newsstory_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
